apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: op4itc2dn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op4itc2dn-python 
  name: op4itc2dn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: op4itc2dn-python 
